# Generated by Django 2.0.2 on 2018-03-18 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('second_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('family_connection', models.IntegerField(choices=[(-1, 'undefined'), (1, 'mother'), (2, 'father'), (3, 'foster_parent')], default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('second_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64)),
                ('carers', models.ManyToManyField(to='kindergarten_app.Carer')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kindergarten_app.Child')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('second_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('type_of_teacher', models.IntegerField(choices=[(-1, 'dundefined'), (1, 'pre-school educator'), (2, 'pedagogue'), (3, 'psychologist'), (4, 'pre-school help'), (5, 'pre-school teacher')])),
                ('groups', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kindergarten_app.Groups')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
    ]
