# Generated by Django 2.0.2 on 2018-03-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_guardian',
            field=models.ManyToManyField(to='kindergarten_app.Teacher'),
        ),
    ]
