# Generated by Django 2.0.2 on 2018-03-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_app', '0003_trip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='type_of_teacher',
            field=models.IntegerField(choices=[(-1, 'undefined'), (1, 'pre-school educator'), (2, 'pedagogue'), (3, 'psychologist'), (4, 'pre-school help'), (5, 'pre-school teacher')]),
        ),
    ]
