# Generated by Django 2.0.2 on 2018-03-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_app', '0004_auto_20180318_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='group',
            field=models.IntegerField(choices=[(0, 'UNDEFINED'), (2, 'BLUE GROUP'), (1, 'GREEN GROUP')], default=0),
        ),
    ]
