# Generated by Django 2.0.2 on 2018-03-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_app', '0005_child_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='group',
            field=models.IntegerField(choices=[(2, 'BLUE GROUP'), (1, 'GREEN GROUP'), (0, 'UNDEFINED')], default=0),
        ),
    ]
