# Generated by Django 2.0.2 on 2018-03-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_app', '0007_auto_20180319_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='second_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='group',
            field=models.IntegerField(choices=[(2, 'BLUE GROUP'), (1, 'GREEN GROUP'), (0, 'UNDEFINED')], default=0),
        ),
    ]
