# Generated by Django 2.0.2 on 2018-03-20 09:10

from django.db import migrations, models
import kindergarten_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_app', '0011_auto_20180319_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='group',
            field=models.IntegerField(choices=[(1, 'Grupa Zielona'), (0, 'Nieokreślona'), (2, 'Grupa Niebieska')], default=0),
        ),
        migrations.AlterField(
            model_name='child',
            name='year_of_birth',
            field=models.IntegerField(null=True, validators=[kindergarten_app.validators.check_number]),
        ),
    ]
