# Generated by Django 2.0.2 on 2018-03-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_app', '0012_auto_20180320_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='year_of_birth',
        ),
        migrations.AlterField(
            model_name='child',
            name='group',
            field=models.IntegerField(choices=[(1, 'Grupa Zielona'), (2, 'Grupa Niebieska'), (0, 'Nieokreślona')], default=0),
        ),
    ]
