# Generated by Django 2.0.2 on 2018-03-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_app', '0014_auto_20180320_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='groups',
            name='member',
        ),
        migrations.RemoveField(
            model_name='child',
            name='group',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='groups',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='type_of_teacher',
            field=models.IntegerField(choices=[(-1, 'nieokreślony'), (1, 'wychowawca przedszkolny'), (2, 'pedagog'), (3, 'psycholog'), (4, 'pomoc wychowawcy'), (5, 'nauczyciel przedszkolny')]),
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.AddField(
            model_name='teacher',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kindergarten_app.Group'),
        ),
    ]
