# Generated by Django 2.0.2 on 2018-03-20 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_app', '0015_auto_20180320_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kindergarten_app.Group'),
        ),
    ]
