# Generated by Django 2.0.2 on 2018-03-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_app', '0016_child_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='second_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
