# Generated by Django 2.0.2 on 2018-03-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_app', '0017_auto_20180320_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carer',
            name='second_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='second_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
