# Generated by Django 2.0.2 on 2018-03-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_app', '0018_auto_20180320_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField()),
                ('present', models.NullBooleanField()),
                ('child', models.ForeignKey(on_delete=None, to='kindergarten_app.Child')),
            ],
        ),
    ]
