# Generated by Django 2.0.2 on 2018-03-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_app', '0019_presencelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='members_of_trips',
            field=models.ManyToManyField(to='kindergarten_app.Child'),
        ),
    ]
