# Generated by Django 2.0.2 on 2018-03-21 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_app', '0020_trip_members_of_trips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='members_of_trips',
            new_name='members_of_trip',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='trip_guardian',
            new_name='trip_guardians',
        ),
        migrations.AlterField(
            model_name='child',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_set', to='kindergarten_app.Group'),
        ),
    ]
