# Generated by Django 2.0.2 on 2018-03-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_app', '0021_auto_20180321_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencelist',
            name='group',
            field=models.ManyToManyField(to='kindergarten_app.Group'),
        ),
    ]
