# Generated by Django 2.0.2 on 2018-03-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_app', '0022_presencelist_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presencelist',
            name='child',
        ),
        migrations.RemoveField(
            model_name='presencelist',
            name='group',
        ),
        migrations.RemoveField(
            model_name='presencelist',
            name='present',
        ),
    ]
