# Generated by Django 2.0.2 on 2018-03-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_app', '0023_auto_20180321_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencelist',
            name='children',
            field=models.ManyToManyField(to='kindergarten_app.Child'),
        ),
        migrations.AddField(
            model_name='presencelist',
            name='group',
            field=models.ForeignKey(default=1, on_delete=None, to='kindergarten_app.Group'),
            preserve_default=False,
        ),
    ]
